### ISSUE TITLE
Use numpy.linalg.cholesky instead of scipy

### ISSUE THREAD

**Issue by lucianopaz** [aesara-devs/aesara#815] opened 2022-02-10 09:40 UTC
## Description of your problem or feature request

Numpy's [Cholesky decomposition](https://numpy.org/doc/stable/reference/generated/numpy.linalg.cholesky.html) can handle arrays of any dimension, as long as their last two dimensions have the same length. Scipy's [Cholesky decomposition](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.cholesky.html) is restricted to using only 2-D arrays.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
from scipy import linalg as sa

a = np.random.randn(10, 3, 3)
b = (np.moveaxis(a, -1, -2) @ a)
c = np.linalg.cholesky(b)  # Returns a (10, 3, 3) array
d = sa.cholesky(b)  # Raises ValueError: Input array needs to be 2D but received a 3d-array.
```

I would like to add an Op that wraps numpy's `cholesky` function and add it to `aesara.tensor.nlinalg`. Luckily, both [jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.cholesky.html) and [numba](https://numba.pydata.org/numba-doc/latest/developer/autogen_numpy_listing.html) already support `numpy.linalg.cholesky`, so we can register those for dispatching.

**Comment by ricardoV94** [comment] 2022-02-10 09:53
Duplicate of #791

**Closed** 2022-02-10 09:54 UTC
