### ISSUE TITLE
Memory leak in reshape

### ISSUE THREAD

**Issue by lucianopaz** [aesara-devs/aesara#851] opened 2022-03-10 22:04 UTC
## Description of your problem or feature request

**Please provide a minimal, self-contained, and reproducible example.**
```python
import os
import psutil
import aesara
from aesara import tensor as at


process = psutil.Process(os.getpid())
old_rss = None
n = 100_000

x = at.sharedvar.TensorSharedVariable(
    "test", at.type.dvector, np.ones(n), strict=True
)
y = at.reshape(x, [-1, 1])
f = aesara.function([], y)
for i in range(100):
    x.set_value(np.ones(n))
    f()
    if i % 10 == 0:
        new_rss = process.memory_info().rss
        if old_rss is not None:
            print(f"Python process increased RSS by {round((new_rss - old_rss) / 1024**2, 2)} MB")
        old_rss = new_rss
```

**Please provide the full traceback of any errors.**
```python
Python process increased RSS by 6.62 MB
Python process increased RSS by 7.74 MB
Python process increased RSS by 7.64 MB
Python process increased RSS by 7.68 MB
Python process increased RSS by 7.64 MB
Python process increased RSS by 7.68 MB
Python process increased RSS by 7.41 MB
Python process increased RSS by 7.63 MB
Python process increased RSS by 7.85 MB
```

**Please provide any additional information below.**

This happens when the reshape operation is compiled to C. When I run the same code setting `aesara.config.cxx = ""`, the Python process does not increase RSS.

## Versions and main components

* Aesara version: 2.4.0
* Aesara config (`python -c "import aesara; print(aesara.config)"`)
* Python version: 3.9
* Operating system: Ubuntu 18.04
* How did you install Aesara: (conda/pip) pip

**Comment by brandonwillard** [comment] 2022-03-11 00:09
This graph ends up being an `InplaceDimShuffle` after optimization.  Using `aesara.function([], y, mode=Mode(optimizer=None))` produces a graph with a  `Reshape` that doesn't demonstrate a memory leak, so this issue is a duplicate of #852.

**Closed by brandonwillard** 2022-03-11 00:09 UTC
Labels: bug, duplicate, important, C-backend, performance concern
