### ISSUE TITLE
Incorrect result for AdvancedIncSubtensor in numba backend

### ISSUE THREAD

**Issue by aseyboldt** [aesara-devs/aesara#987] opened 2022-06-08 18:13 UTC
The numba implementation of `AdvancedIncSubtensor1` (and probably also `AdvancedIncSubtensor`) returns incorrect results if indices are used more than once:
```python
import aesara
import numba
import aesara.tensor as at
import numpy as np

x = at.dvector("x")
y = x[np.zeros(2, dtype=int)]
z = y.sum()

func = aesara.function([x], [z, at.grad(z, x)])
func2 = aesara.function([x], [z, at.grad(z, x)], mode=aesara.compile.NUMBA)

data = np.random.default_rng(42).normal(size=1)

func(data)
# Output is the correct [array(0.60943416), array([2.])]

func2(data)
# Output is [0.6094341595088627, array([1.])]
```
This is because it uses code like this:
```python
data = np.zeros(2)
data[[0, 0]] += 1
data
```
but due to buffering this only increments data[0] once instead of twice.

If we add a different implementation for the op it works fine:

```python
@aesara.link.numba.dispatch.numba_funcify.register(aesara.tensor.subtensor.AdvancedIncSubtensor1)
def numba_funcify_IncSubtensor(op, node, **kwargs):

    def incsubtensor_fn(z, vals, idxs):
        z = z.copy()
        for idx, val in zip(idxs, vals):
            z[idx] += val
        return z

    return aesara.link.numba.dispatch.basic.numba_njit(incsubtensor_fn)
```

**Comment by ricardoV94** [comment] 2022-06-08 19:35
I think this is a duplicate of https://github.com/aesara-devs/aesara/issues/603

But since you have a working solution, would you like to open a PR?

**Closed** 2022-06-09 17:24 UTC
Labels: duplicate
