### ISSUE TITLE
Memory leak in `DimShuffle`

### ISSUE THREAD

**Issue by lucianopaz** [aesara-devs/aesara#852] opened 2022-03-10 22:04 UTC
## Description of your problem or feature request

**Please provide a minimal, self-contained, and reproducible example.**
```python
import os
import psutil
import aesara
from aesara import tensor as at


process = psutil.Process(os.getpid())
old_rss = None
n = 100_000

x = at.sharedvar.TensorSharedVariable(
    "test", at.type.dvector, np.ones(n), strict=True
)
y = x.dimshuffle([0, "x"])
f = aesara.function([], y)
for i in range(100):
    x.set_value(np.ones(n))
    f()
    if i % 10 == 0:
        new_rss = process.memory_info().rss
        if old_rss is not None:
            print(f"Python process increased RSS by {round((new_rss - old_rss) / 1024**2, 2)} MB")
        old_rss = new_rss
```

**Please provide the full traceback of any errors.**
```python
Python process increased RSS by 6.62 MB
Python process increased RSS by 7.74 MB
Python process increased RSS by 7.64 MB
Python process increased RSS by 7.68 MB
Python process increased RSS by 7.64 MB
Python process increased RSS by 7.68 MB
Python process increased RSS by 7.41 MB
Python process increased RSS by 7.63 MB
Python process increased RSS by 7.85 MB
```

**Please provide any additional information below.**

This happens when the reshape operation is compiled to C. When I run the same code setting `aesara.config.cxx = ""`, the Python process does not increase RSS.

## Versions and main components

* Aesara version: 2.4.0
* Aesara config (`python -c "import aesara; print(aesara.config)"`)
* Python version: 3.9
* Operating system: Ubuntu 18.04
* How did you install Aesara: (conda/pip) pip

**Comment by lucianopaz** [comment] 2022-03-10 22:05
This is very similar to #851 but I thought that it had to be an issue of its own

**Comment by twiecki** [comment] 2022-03-10 22:44
If it's in 3 `Ops` I wonder if it's in more (or if it's something more general non-op-specific), maybe we can just run this on all Ops somehow.

**Comment by brandonwillard** [comment] 2022-03-10 22:47
> If it's in 3 `Ops` I wonder if it's in more (or if it's something more general non-op-specific), maybe we can just run this on all Ops somehow.

It's possible that the issue involves the `CVM` or shared variable code.

**Comment by andrejmuhic** [comment] 2022-03-10 23:13
I was playing with this and I think the bug was introduced in 2.3.3 tag release.
https://github.com/aesara-devs/aesara/compare/rel-2.3.2...rel-2.3.3
I think the leak in https://github.com/aesara-devs/aesara/issues/849 could be caused by the leak in reshape reported here:
https://github.com/aesara-devs/aesara/issues/851
The 2.3.2 is the first version that does not exhibit the leak in the issue 849

**Comment by brandonwillard** [comment] 2022-03-11 00:44
Looks like we're not removing a reference to `_input` [here](https://github.com/aesara-devs/aesara/blob/3d8553f7b56caed8686e3db9bfbe5ffea110b70a/aesara/tensor/c_code/dimshuffle.c#L17).

**Comment by brandonwillard** [comment] 2022-03-11 02:07
This is a duplicate of https://github.com/aesara-devs/aesara/issues/849.

**Closed** 2022-03-11 04:25 UTC
Labels: bug, duplicate, important, C-backend, performance concern
